FROM golang:1.10 as BUILD

RUN mkdir -p /go/src/github.com/chongzii6 \
  && cd /go/src/github.com/chongzii6 \
  && git clone https://github.com/chongzii6/haproxy-kube-agent.git \
  && cd haproxy-kube-agent \
  && rm -rf vendor \
  && tar xf v3.tar.gz \
  && go build

###
FROM golang:1.10

RUN mkdir -p /go/bin/config
COPY --from=BUILD /go/src/github.com/chongzii6/haproxy-kube-agent/haproxy-kube-agent /go/bin
COPY --from=BUILD /go/src/github.com/chongzii6/haproxy-kube-agent/agent.yml /go/bin
COPY --from=BUILD /go/src/github.com/chongzii6/haproxy-kube-agent/certs /go/bin
WORKDIR /go/bin

CMD ["haproxy-kube-agent","--config=agent.yml"]
